services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    environment:
      - QDRANT__SERVICE__API_KEY=${QDRANT_API_KEY:-}
    volumes:
      - qdrant_storage:/qdrant/storage

  api:
    build:
      context: ../../Downloads
      dockerfile: docker/api.Dockerfile
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - qdrant

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  qdrant_storage:
    driver: local

